# TrackScooter Mobile Versioning
# Format Semantic Versioning: MAJOR.MINOR.PATCH
# - MAJOR: Perombakan arsitektur / UI masif
# - MINOR: Fitur baru selesai & stabil
# - PATCH: Bugfix, tweak UI, performa, konfigurasi (gunakan ini untuk perubahan kecil)
VERSION_MAJOR=2
VERSION_MINOR=7
VERSION_PATCH=17
VERSION_BUILD=28
